version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
        - checkout
        - run:
            name: Create Python VirtualEnv
            command: virtualenv helloworld && . helloworld/bin/activate && pip install FLASK_CONFIG
        - run:
            name: Run Tests
            command: python test_hello_world.py