version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
        - checkout
        - run:
            name: Create Python VirtualEnv
            command: |
              virtualenv helloworld
              . helloworld/bin/activate
              pip install flask pyinstaller
        - run:
            name: Run Tests
            command: |
              . helloworld/bin/activate
              python test_hello_world.py
        - run:
            name: Build Python Binary
            command: |
              . helloworld/bin/activate
              pyinstaller -F hello_world.py